### ISSUE TITLE
Server side error crashes server before it finishes loading [natural_absorption-1.12-1.3.0.jar]

### ISSUE THREAD

**Issue by renadi** [KnightMiner/UnnaturalAbsorption#1]
https://pastebin.com/NPJ2mZLR

Basically when I try to start a server this is the result.  My guess is it's trying to show a tooltip server side?

**Comment by KnightMiner** [comment]
Probably missed marking a class sideonly somewhere. I'll look into it.

**Comment by KnightMiner** [comment]
Fixed by 6b75c37. Will be in the next release

**Comment by Darkmega18** [comment]
ah, jolly good. just waiting on this one then also.

**Comment by KnightMiner** [comment]
Fixed in 1.3.1
