### ISSUE TITLE
[Suggestion] Possible to add support for "Construct's Armory"? Like an Absorption Modifier on their armors or something.

### ISSUE THREAD

**Issue by SonicX8000** [KnightMiner/UnnaturalAbsorption#3]
There's a Tinker's Construct mod addon called "Construct's Armory" that allows you to create armor out of materials, such as having Cobalt Armor, Ardite Armor or a mix of materials on the armors to get varies effects, durability, etc.

Since there are Absorption Enchantments that can be applied on Vanilla/Modded armors in the "Unnatural Absorption"... these armors from Construct's Armory uses a modifier system to get these 'enchantments'. Would it be possible to add in support for an Absorption Modifier to be applied on their armors? I was thinking maybe X amount of Golden Apples can be used to gain 1 Rank of Absorption, up to a max Rank of 5 since the enchantment books cap out at Rank 5.

I understand that you didn't want to plan on putting too much work than what you've already done but it wouldn't hurt to ask about it. Forgive me for your time if you look at this.

**Comment by KnightMiner** [comment]
I'm pretty sure Constructs Armory already has an absorption modifier. In any case, it definitely has a health modifier which is a pretty similar end result, so I cannot see myself adding this. Remember, all this mod does is expose a vanilla mechanic, any mod can expose the same mechanic themselves.
