### ISSUE TITLE
[Bugs] Some issues/bugs!

### ISSUE THREAD

**Issue by Akitori** [KnightMiner/UnnaturalAbsorption#5]
Hoi! Let's get this done quickly.

Iron wine from Rustic doesn't work, the hearts appear before poofing away into the void! (would assume it affects any mod that adds absorption hearts directly rather than potion effect)

Absorption hearts on multiplayer `reset` when server is restarted. Hearts reappear after taking damage/using some absorption books. The book part is the more concerning, as people are using experience for little if anything, just to fix the bug.

Hearts don't appear in nether/end when swapped, though i suppose that's more visual than anything.

**Comment by KnightMiner** [comment]
I have a partial fix for the first issue, problem is it has some sideeffects with the armor enchantment that I need to deal with. Second one I will look into, no idea what is going on with the last one as they work perfectly fine in the nether and end for me.

Can you please make separate tickets for each of these issues so I can better track the problems?

**Comment by Akitori** [comment]
Sure, I'll get to work on it now.
